format = '''$directory$git_branch$git_status$kubernetes$terraform$go$rust$python$character'''

add_newline = false

palette = 'colors'

[palettes.colors]
color1 = '#ffb59a'
color2 = '#552009'
color3 = '#d8c2bb'
color4 = '#271e1a'
color5 = '#552009'
color6 = '#1a110e'
color7 = '#1a110e'
color8 = '#ffb59a'
color9 = '#d4c78e'

# Prompt symbols 
[character]
success_symbol = "[❯](color9 bold)"
error_symbol = "[x](#ffb4ab bold)"
vicmd_symbol = "[❮](color9 bold)"

[directory]
format = "[$path]($style)( $read_only)($style) "
read_only = ''
style = "fg:color3 bg:color7"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'color9 bold'

[git_status]
format = '([$all_status$ahead_behind]($style)) ' 
style = "color3 dimmed"
stashed = "≡"

[package]
disabled = true
