format = '''$directory$git_branch$git_status$kubernetes$terraform$go$rust$python$character'''

add_newline = false

palette = 'colors'

[palettes.colors]
color1 = '#bcc3ff'
color2 = '#242b61'
color3 = '#c7c5d0'
color4 = '#1f1f25'
color5 = '#242b61'
color6 = '#131318'
color7 = '#131318'
color8 = '#bcc3ff'
color9 = '#e6bad7'

# Prompt symbols 
[character]
success_symbol = "[❯](color9 bold)"
error_symbol = "[x](#ffb4ab bold)"
vicmd_symbol = "[❮](color9 bold)"

[directory]
format = "[$path]($style)( $read_only)($style) "
read_only = ''
style = "fg:color3 bg:color7"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'color9 bold'

[git_status]
format = '([$all_status$ahead_behind]($style)) ' 
style = "color3 dimmed"
stashed = "≡"

[package]
disabled = true
