format = '''$directory$git_branch$git_status$kubernetes$terraform$go$rust$python$character'''

add_newline = false

palette = 'colors'

[palettes.colors]
color1 = '#81d3dd'
color2 = '#00363b'
color3 = '#bec8c9'
color4 = '#1a2121'
color5 = '#00363b'
color6 = '#0e1415'
color7 = '#0e1415'
color8 = '#81d3dd'
color9 = '#b8c6ea'

# Prompt symbols 
[character]
success_symbol = "[❯](color9 bold)"
error_symbol = "[x](#ffb4ab bold)"
vicmd_symbol = "[❮](color9 bold)"

[directory]
format = "[$path]($style)( $read_only)($style) "
read_only = ''
style = "fg:color3 bg:color7"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
format = '[$branch(:$remote_branch)]($style) '
style = 'color9 bold'

[git_status]
format = '([$all_status$ahead_behind]($style)) ' 
style = "color3 dimmed"
stashed = "≡"

[package]
disabled = true
